### ISSUE TITLE
Doesn't work if retain query string is unchecked

### ISSUE THREAD

**Issue by njt1982** [md-systems/redirect#70] opened 2015-12-16 10:31 UTC
I am running nginx + Perusio config.

I installed the latest 8.x release from this repo. I created a test redirect (node/123 > a valid article). When I visit http://site.dev/node/123 with query string retaining disabled, I get a 404. When retaining is enabled, I get a proper redirect, but I also get `?q=node/123` appending to my URL.

Neither are ideal, but the later at least redirects.

I assume this is a bug, not intended functionality?

**Comment by nolfranklin** [comment] 2016-01-14 22:11
Any luck with fixing this issue?

**Comment by njt1982** [comment] 2016-03-04 13:27
The latest dev release still does this, although now I get ?q= appended in all redirects, regardless of the retain query string!

**Comment by njt1982** [comment] 2016-03-04 13:29
Hmm it looks like it may be a Perusio config problem...

I just made this change:

```
- fastcgi_param QUERY_STRING q=$uri&$args;
+ fastcgi_param QUERY_STRING $args;
```

And I no longer get this problem.

**Comment by Berdir** [comment] 2016-03-04 13:32
Yes, I suspected something like that, since I couldn't reproduce this with Apache. Drupal 8 doesn't use q anymore, except in autocomple callbacks (where it is actually the query/search string now).

Closing this.

**Closed as completed by Berdir** 2016-03-04 13:32 UTC

**Comment by njt1982** [comment] 2016-03-04 13:33
I have opened https://github.com/perusio/drupal-with-nginx/issues/242 with Perusio. That line doesn't seem to affect D7 sites either (at least "it works for me locally" ! ).

**Comment by kyvour** [comment] 2017-03-07 06:53
Seems like fastcgi_param QUERY_STRING $args; broke batch processes on drupal 8-4.x

Probably there is need to make this change:
`- fastcgi_param QUERY_STRING q=$uri&$args;
+ fastcgi_param QUERY_STRING $query_string;`
